### ISSUE TITLE
Consider replacing applause dependency

### ISSUE THREAD

**Issue by mikecbrant** [outaTiME/gulp-replace-task#11]
The applause dependency has both moderate and low severity vulnerabilities, but it seems that library might not be actively maintained (there is an almost year-old old pull request to fix the issue there than have not been accepted see https://github.com/outatime/applause/pulls).

Is it appropriate to replace this dependency?

**Comment by lifenstein** [comment]
It does look like `applause` is abandoned. There's a fork with updated dependencies: https://github.com/gbochenek/next-applause

**Comment by outaTiME** [comment]
Sorry, finally after so much time I updated the dependencies in the new version of this plugin to fix the incompatibility and vulnerabilities problems.
