### ISSUE TITLE
How to get file basename as part of the "replacement"

### ISSUE THREAD

**Issue by marcodings** [outaTiME/gulp-replace-task#2]
Please forgive me for asking here also. as I don't know this something that can be solved generically,
or if its something that needs "enhancement" of the plugin

http://stackoverflow.com/questions/31612192/get-file-basename-in-gulp-replacer-task

thanks in advance for any feedback

**Comment by outaTiME** [comment]
Hi pal, this issue is related to: 

https://github.com/outaTiME/applause/issues/5
