### ISSUE TITLE
Nested JSON does not work as expected

### ISSUE THREAD

**Issue by mattpwalsh** [outaTiME/gulp-replace-task#3]
The documentation says that nested JSON would be replaced as a string representation

From examples:

```
var gulp = require('gulp');
var replace = require('gulp-replace-task');

gulp.task('default', function () {
  gulp.src('test.html')
    .pipe(replace({
      patterns: [
        {
          json: {
            "key": "value",   // replaces "@@key" to "value"
            "inner": {        // replaces "@@inner" with string representation of "inner" object
              "key": "value"  // replaces "@@inner.key" to "value"
            }
          }
        }
      ]
    }))
    .pipe(gulp.dest('build'));
});
```

test.html

```
@@inner
```

After running, this is the content of dist/test.html

```
[object Object]
```

I would expect something like this:

```
{ "key": "value"}
```

That seems to be how the grunt version works (I'm switching from grunt to gulp).

**Comment by outaTiME** [comment]
Hi pal, 

I will check right now ... which version of grunt-replace (from) / gulp-replace-task (to) are you using ??

**Comment by outaTiME** [comment]
Yup, it fails ... I'll be fixing soon ... this issue comes from applause core lib:

https://github.com/outaTiME/applause

Check out my new tests:

![screen shot 2015-08-27 at 16 10 16](https://cloud.githubusercontent.com/assets/140472/9530500/9a030e72-4cd6-11e5-9351-f7e1ead68ba4.png)

^^

**Comment by outaTiME** [comment]
Hi pal, im still working on these ...

Im building new version of applause (https://github.com/outaTiME/applause) for better replace handling ... stay in touch ...

thks !

**Comment by outaTiME** [comment]
Finally, the last version of `gulp-replace-task` (0.11.0) using `applause` (1.1.0) closes this issue ...

thks, and please check again ...
