### ISSUE TITLE
Not able to replace strings. 

### ISSUE THREAD

**Issue by luckybusted** [outaTiME/gulp-replace-task#8]
I am not able to replace **strings** anymore.
It have to be a RegEx. 

Is it only me or did anyone else has this issue?

**Comment by kojilab** [comment]
i tried this package and couldn't get it to work

**Comment by jkndrkn** [comment]
It's not just you. I was neither able to replace strings nor regex. I am using node 8.14.0 on macOS. I have switched to gulp-replace and have had more success with that.

https://www.npmjs.com/package/gulp-replace

**Comment by outaTiME** [comment]
Sorry, finally after so much time I updated the dependencies in the new version of this plugin to fix the incompatibility and vulnerabilities problems.
